sonar.organization=edlozano19
sonar.projectKey=edlozano19_tome

sonar.projectName=Tome

#Source code to analyze
sonar.sources=backend/src/main,frontend/src

#Test code
sonar.tests=backend/src/test

#Stay out of build artifacts and dependencies
sonar.exclusions=**node_modues/**,**/dist/**,**/target/**,**/.mvn/**

#Encoding
sonar.sourceEncoding=UTF-8