spring:
  application:
    name: tome
  datasource:
    url: jdbc:postgresql://localhost:5432/tome
    username: tome
    password: tome
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB

management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:5173"
        allowed-methods: GET

tome:
  jwt:
    secret: "+/#k'eGFzVsj8h:;8LY,t|4mvd6RQkEH"
    access-token-ttl-minutes: 15
    refresh-token-ttl-days: 13
  storage:
    epub-dir: ./storage/epubs