spring:
  application:
    name: tome
  datasource:
    url: jdbc:postgresql://localhost:5432/tome
    username: tome
    password: tome
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:5173"
        allowed-methods: GET
